# Generated by Django 4.2.2 on 2024-10-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="payment_comments",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("online", "Online"),
                    ("other", "Other"),
                ],
                default="cash",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
